import { Product, StoreConfig } from './types';

export const STORE_CONFIG: StoreConfig = {
  name: "Warung Marjuki'S",
  owner: "Ibu Yulia",
  tagline: "Selamat Datang di Warung Marjuki'S",
  subtitle: "Makanan Rumahan Lezat, Murah, Bersih, dan Dibuat Setiap Hari.",
  address: {
    street: "JL. Jomblang Perbalan No.800",
    rtRw: "RT 02 RW 01",
    city: "Semarang",
    province: "Jawa Tengah",
    country: "Indonesia",
    fullAddress: "JL. Jomblang Perbalan No.800 RT 02 RW 01, Semarang, Jawa Tengah, Indonesia",
  },
  openingHours: "Senin - Minggu (06.00 - 21.00 WIB)",
  phone: "+62 882-0051-16301",
  whatsappNumber: "62882005116301", // Easily replaceable WhatsApp number format: 62xxxxxxxxx
  googleMapsUrl: "https://maps.google.com/?q=JL.+Jomblang+Perbalan+No.800+Semarang",
  googleMapsEmbed: "https://maps.google.com/maps?q=JL.+Jomblang+Perbalan+No.800+Semarang&t=&z=16&ie=UTF8&iwloc=&output=embed"
};

export const PRODUCTS: Product[] = [
  {
    id: "soto",
    name: "Soto Ayam Rumahan",
    category: "makanan",
    price: 8000,
    description: "Soto ayam hangat dengan kuah kaya rempah khas Semarang, potongan ayam empuk, tauge segar, dan seledri.",
    image: "https://th.bing.com/th/id/OIP.5GAiCRkhollVnd7r8g6upQHaHa?w=181&h=181&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3",
    isBestSeller: true,
    isFeatured: true,
  },
  {
    id: "nasi-rames",
    name: "Nasi Rames Spesial",
    category: "makanan",
    price: 8000,
    description: "Nasi hangat dilengapi dengan lauk pauk rumahan lezat seperti oseng tempe, mie goreng, dan sayur sambel goreng yang nikmat.",
    image: "https://i.pinimg.com/originals/6a/0e/d1/6a0ed1ff8748f190b4e573339b040adc.jpg",
    isBestSeller: true,
    isFeatured: true,
  },
  {
    id: "indomie-biasa",
    name: "Indomie Biasa",
    category: "makanan",
    price: 6000,
    description: "Mie instan favorit (Goreng/Rebus) dimasak pas dengan taburan bawang goreng dan rasanya mantap.",
    image: "https://cdn.kibrispdr.org/data/667/indomie-goreng-hd-39.jpg",
    isBestSeller: false,
    isFeatured: false,
  },
  {
    id: "indomie-telur",
    name: "Indomie Telur",
    category: "makanan",
    price: 8000,
    description: "Mie instan gurih disajikan hangat dengan telur setengah matang/matang dan irisan cabai rawit segar.",
    image: "https://th.bing.com/th/id/OIP.gkLdmTRJSmxK2lUuQcX83AHaFF?r=0&o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    isBestSeller: true,
    isFeatured: true,
  },
  {
    id: "es-teh",
    name: "Es Teh Manis",
    category: "minuman",
    price: 3000,
    description: "Es teh manis racikan asli rumahan, segar membasahi kerongkongan di siang hari.",
    image: "https://tse2.mm.bing.net/th/id/OIP.qlDtVWjb1aaflQkt4PysuQHaJQ?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    isBestSeller: true,
    isFeatured: true,
  },
  {
    id: "es-jeruk",
    name: "Es Jeruk Peras",
    category: "minuman",
    price: 5000,
    description: "Minuman es jeruk peras alami kaya vitamin C, asam manis segar menyegarkan hari Anda.",
    image: "https://th.bing.com/th/id/OIP._nzjdb2k6-y-8vCUa99ZEAHaHa?r=0&o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3",
    isBestSeller: false,
    isFeatured: true,
  },
  {
    id: "mendoan",
    name: "Tempe Mendoan (1 Pcs)",
    category: "gorengan",
    price: 1500,
    description: "Tempe mendoan hangat gurih dengan balutan tepung daun bawang, renyah di luar lembut di dalam.",
    image: "https://tse2.mm.bing.net/th/id/OIP.ZwpD4nqUAfOcAMOF4ncG9gHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    isBestSeller: true,
    isFeatured: true,
  },
  {
    id: "tahu-bakso",
    name: "Tahu Bakso Semarang (1 Pcs)",
    category: "gorengan",
    price: 2500,
    description: "Tahu gurih berisi adonan daging sapi bakso pilihan khas Semarang yang legit dan lezat.",
    image: "https://tse3.mm.bing.net/th/id/OIP.hvEKtU3EzPLOk_6bEDZGxAHaEK?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    isBestSeller: true,
    isFeatured: true,
  },
  {
    id: "bakwan-jagung",
    name: "Bakwan Jagung (1 Pcs)",
    category: "gorengan",
    price: 1500,
    description: "Gorengan jagung manis renyah dengan bumbu rempah pilihan, cocok untuk teman makan.",
    image: "https://tse4.mm.bing.net/th/id/OIP.L8NajE9fNq9yikPVqo4RswHaFP?r=0&rs=1&pid=ImgDetMain&o=7&rm=3",
    isBestSeller: false,
    isFeatured: false,
  },
];
